project_name: kpow
builds:
  - id: kpow
    main: ./main.go
    binary: kpow
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
archives:
  - id: default
    builds:
      - kpow
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - readme.md
      - LICENSE
      - LICENSE-BUSL
      - LICENSE-APACHE
checksum:
  name_template: "checksums.txt"
changelog:
  sort: desc
release:
  draft: false
  prerelease: false
  github:
    owner: sultaniman
    name: kpow
