[key]
key_kind = "pgp"
pubkey_path = "/path/to/pubkey"
password = ""
advertise = ""

[mailer]
dsn = "smtp://user:password@smtp.example.com:587"
from = "sender@example.com"
to = "recipient@example.com"

[server]
title = "KPow"
port = 6543
host = "0.0.0.0"
log_level = "ERROR"
