[server]
title = "KPow"
port = 6543
host = "0.0.0.0"
log_level = "DEBUG"

[key]
kind = "pgp"
path = "server/enc/testkeys/pubkey.asc"
password = ""
advertise = true

[mailer]
dsn = "smtp://user:password@smtp.example.com:587"
from = "sender@example.com"
to = "recipient@example.com"

[inbox]
path = "inbox"
cron = "* * * * *"

[webhook]
url = "http://localhost:8000/webhook"
