[server]
title = "KPow"
port = 6543
host = "0.0.0.0"
log_level = "DEBUG"
message_size = 512
hide_logo = false
custom_banner = "banner.html"

[rate_limiter]
rpm = 20
burst = 5
cooldown = 120

[key]
kind = "pgp"
path = "server/enc/testkeys/pubkey.gpg"
advertise = true

[mailer]
dsn = "smtp://user:secret@localhost:1025"
from = "sender@example.com"
to = "recipient@example.com"
max_retries = 2

[inbox]
path = "inbox"
cron = "* * * * *"

[webhook]
url = "http://localhost:10080/webhook"
