[server]
title = "KPow"
port = 6543
host = "0.0.0.0"
log_level = "DEBUG"

[key]
kind = "age"
path = "key.age"
password = ""
advertise = true

[mailer]
dsn = "smtp://user:password@smtp.example.com:587"
from = "sender@example.com"
to = "recipient@example.com"
